setup workflow

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,21 +1,22 @@
 #!/bin/sh
 
-STAGED_GO_FILES=$(git diff --cached --name-only | grep .go)
-
-# If there are no staged go files then exit
-if [ -z "$STAGED_GO_FILES" ]; then
-  exit 0
-fi
-
 RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
 
-# If there are staged go files then run linter
-make lint
-if [[ $? != 0 ]]; then
-  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-  exit 1
-else
- printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
- exit 0
-fi
+cd modules
+
+MODIFIED_MODULES=$(git diff --name-only origin/main -- . | awk 'BEGIN {FS="/"} NF > 2 && !m[$2]++ {print $2}')
+
+for MODULE in $MODIFIED_MODULES
+do
+    cd $MODULE
+    make lint
+    if [[ $? != 0 ]]; then
+        printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+        exit 1
+    fi
+    cd ..
+done
+
+printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+exit 0
