setup workflow

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -20,26 +20,24 @@ jobs:
       - name: Install golangci-lint
         run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
       - name: Run linter
-        run: ls
-      # - name: Run linter
-      #   run: |
-      #     MODIFIED_MODULES=$(git diff --name-only origin/main -- . | awk 'BEGIN {FS="/"} NF > 2 && !m[$2]++ {print $2}')
+        run: |
+          MODIFIED_MODULES=$(git diff --name-only origin/main -- . | awk 'BEGIN {FS="/"} NF > 2 && !m[$2]++ {print $2}')
           
-      #     [ -z "$MODIFIED_MODULES" ] && { echo "No modified modules found"; exit 1; }
+          [ -z "$MODIFIED_MODULES" ] && { echo "No modified modules found"; exit 1; }
 
-      #     for MODULE in $MODIFIED_MODULES
-      #     do
-      #       cd $MODULE
-      #       $(go env GOPATH)/bin/golangci-lint run --config ../../.golangci.yml
-      #       if [[ $? != 0 ]]; then
-      #           echo "Linting failed for $MODULE"
-      #           exit 1
-      #       fi
-      #       cd ..
-      #     done
+          for MODULE in $MODIFIED_MODULES
+          do
+            cd $MODULE
+            $(go env GOPATH)/bin/golangci-lint run --config ../../.golangci.yml
+            if [[ $? != 0 ]]; then
+                echo "Linting failed for $MODULE"
+                exit 1
+            fi
+            cd ..
+          done
 
-      #     exit 0
-      #   working_directory: modules
+          exit 0
+        working-directory: modules
       # - name: test
       #   run: |
       #     MODIFIED_MODULES=$(git diff --name-only origin/main -- . | awk 'BEGIN {FS="/"} NF > 2 && !m[$2]++ {print $2}')
